# Generated by Django 4.0.6 on 2022-07-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_ninja_jitsus_ninja_dislikes_ninja_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninja',
            name='jitsus',
            field=models.ManyToManyField(to='main_app.jitsu'),
        ),
    ]
